### ISSUE TITLE
PROYECTO FINAL EQUIPO 7

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-7#1]
EQUIPO:
Jaczibeth Cruz Ramirez
Betsabe Aricel Castro Rodriguez
Irvin Jimenez Sanchez
(Trabajo corregido)
[PROYECTO FINAL.EQUIPO7.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-7/files/10214500/PROYECTO.FINAL.EQUIPO7.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
36.4 de 50, aparecen dos nombres diferentes  del proyecto ¿Cúal es?, luego aparecen dos objetivos generales, uno como objetivo del proyecto y otro en objetivos generales ¿?, el objetivo general solo uno de todo el proyecto, los objetivos especificos no estan bien redactados, los invito a que consulten información de como se redacta un objetivo,  respecto a las actividades especificas son las actividades que hicieron en su proyecto no eso que ustedes pusieron, en el marco teórico se cita el año en que se consulto la informacion adelante de la pagina o el autor, no lleva una concluison tampoco lleva lo de bibliografias, eso va despues en otro capitulo del proyecto.

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos días equipo 7, me siguen apareciendo dos nombres diferentes del proyecto uno en la portada y otro en el apartado nombre del proyecto, respecto a la descripción de las actividades, las cuáles tienen que ir redactadas en infinitivo, y por último su Marco teórico la bibliografía en norma APA va al final, 45.22 de 50

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos días equipo 7, me siguen apareciendo dos nombres diferentes del proyecto uno en la portada y otro en el apartado nombre del proyecto, respecto a la descripción de las actividades, las cuáles tienen que ir redactadas en infinitivo, y por último su Marco teórico la bibliografía en norma APA va al final, 45.22 de 50

**Comment by josealfredo79** [comment]
Bien hecho y revisado
